blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/delete/', views.post_delete, name='post_delete'),

]

cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>/', add, name='product_add'),
    path('remove/<product_id>/', remove, name='product_remove'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from accounts import views
from shop import views
from config import settings

urlpatterns = [
    # path('', main, name='main_product_all'),
    # path('<slug:category_slug>/', views.main, name='main_category_all'),
    path('', views.main, name='main_product_all'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('shop/', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('coupon/', include('coupon.urls')),
    path('weather/', include('weather.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coupon/urls.py
from django.urls import path

from .views import add_coupon
app_name = 'coupon'

urlpatterns = [
    path('add/', add_coupon, name='add'),
]

order/urls.py
from django.urls import path
from .views import *
app_name = 'orders'
urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('create_ajax/', OrderCreateAjaxView.as_view(), name='order_create_ajax'),
    path('checkout/', OrderCheckoutAjaxView.as_view(), name='order_checkout'),
    path('validation/', OrderImpAjaxView.as_view(), name='order_validation'),
    path('complete/', order_complete, name='order_complete'),
    path('order_detail/<int:order_id>/', admin_order_detail,name='admin_order_detail'),
    path('order_list/', order_list, name='order_list'),
]

shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', product_in_category, name='product_all'),
    path('<slug:category_slug>/', product_in_category, name='product_in_category'),
    path('<int:id>/<product_slug>/', product_detail, name='product_detail'),
    path('search', search, name='search'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

# 클라이언트 화면에 입력 폼을 만들어주려고
# 클라이언트가 입력한 데이터에 대한 전처리


class AddProductForm(forms.Form):
    quantity = forms.IntegerField(label="수량")
    is_update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from order.models import OrderItem
from shop.models import Product
from coupon.forms import AddCouponForm

from .forms import AddProductForm
from .cart import Cart


@require_POST
def add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    # 클라이언 -> 서버로 데이터를 전달
    # 유효성 검사, injection 전처리
    form = AddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], is_update=cd['is_update'])

    return redirect('cart:detail')


def remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:detail')


def detail(request):
    cart = Cart(request)
    add_coupon = AddCouponForm()
    products = Product.objects.all()
    orderitem = OrderItem.objects.all()

    for product in cart:
        product['quantity_form'] = AddProductForm(initial={'quantity': product['quantity'], 'is_update': True})

    return render(request, 'cart/detail.html', {'cart': cart
        , 'add_coupon': add_coupon
        , 'products': products
        , 'orderitem': orderitem})

cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}
Shopping Cart
{% endblock %}

{% block content %}
<style xmlns:shop="http://www.w3.org/1999/xhtml">
    .table{
    width:90%;
    margin:3% auto;
    }
    .text-right{
    margin:0% 5%;
    }
    #id_quantity{
    text-align:right;
    width:70px;
    }
    .coupon{
    margin: 0% 5%;
    }
    th{
    text-align:center;
    }
    td{
        text-align:center;
    }
</style>
<table class="table table-striped" xmlns:cart="http://www.w3.org/1999/xhtml" xmlns:shop="http://www.w3.org/1999/xhtml"
       xmlns:shop="http://www.w3.org/1999/xhtml" xmlns:shop="http://www.w3.org/1999/xhtml"
       xmlns:orders="http://www.w3.org/1999/xhtml" xmlns:orders="http://www.w3.org/1999/xhtml"
       xmlns:shop="http://www.w3.org/1999/xhtml" xmlns:shop="http://www.w3.org/1999/xhtml">
        <thead>
            <tr>
                <th scope="col" width="20%">상품이미지 </th>
                <th scope="col">상품 </th>
                <th scope="col" width="15%">수량 </th>
                <th scope="col">삭제</th>
                <th scope="col">개별 금액</th>
                <th scope="col">합산 금액 </th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                <tr>
                    <th scope="row">
                        <a href="{{product.get_absolute_url}}">
                            <img src="{{product.image.url}}" class="img-thumbnail">
                        </a>
                    </th>
                    <td>{{product.name}}</td>
                    <td>
                        <form action="{% url 'cart:product_add' product.id %}" method="post">
                            {% csrf_token %}
                            {{item.quantity_form.quantity}}
                            {{item.quantity_form.is_update}}
                            <input type="submit" class="btn btn-outline-secondary btn-sm" value="수량변경">
                        </form>
                    </td>
                    <td><a href="{% url 'cart:product_remove' product.id%}">삭제하기</a></td>
                    <td class="num">{{item.price|intcomma}}</td>
                    <td class="num">{{item.total_price|intcomma}}</td>
                </tr>
            {% endwith %}
            {% endfor %}
            {% if cart.coupon %}<!--#쿠폰이 있을때만 열림-->
            <tr class="total">
                <td>할인전 금액</td>
                <td colspan="4"></td>
                <td class="num">{{cart.get_product_total|intcomma}}</td>
            </tr>
            <tr class="coupon">
                <td>{{cart.coupon.code}} 쿠폰 </td>
                <td colspan="4"></td>
                <td>- {{cart.get_discount_total|intcomma}}</td>
            </tr>
            {% endif %}<!— 쿠폰이 없을 경우 아래 코드로 진행—>
        <tr class="coupon">
            <td>총 금액</td>
            <td colspan="4"></td>
            <td class="num">{{cart.get_total_price|intcomma}}</td>
        </tr>
        </tbody>
    </table>
<div class="coupon">
    <form action="{% url 'coupon:add' %}" method="post">
        {% csrf_token %}
        {{add_coupon}}
        <input type="submit" class="btn btn-outline-secondary btn-sm" value="등록">
    </form>
</div>
<br>
    <p class="text-right">
        <a href="{% url "shop:product_all" %}" class="btn btn-outline-secondary">쇼핑 계속하기</a>
        <a href="{% url "orders:order_create" %}" class='btn btn-outline-secondary'>구매하기</a>

    </p>
{% endblock %}