blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/delete/', views.post_delete, name='post_delete'),

]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from accounts import views
from shop import views
from config import settings

urlpatterns = [
    # path('', main, name='main_product_all'),
    # path('<slug:category_slug>/', views.main, name='main_category_all'),
    path('', views.main, name='main_product_all'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('shop/', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('coupon/', include('coupon.urls')),
    path('weather/', include('weather.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from .views import *
app_name = 'orders'
urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('create_ajax/', OrderCreateAjaxView.as_view(), name='order_create_ajax'),
    path('checkout/', OrderCheckoutAjaxView.as_view(), name='order_checkout'),
    path('validation/', OrderImpAjaxView.as_view(), name='order_validation'),
    path('complete/', order_complete, name='order_complete'),
    path('order_detail/<int:order_id>/', admin_order_detail,name='admin_order_detail'),
    path('order_list/', order_list, name='order_list'),
]

shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', product_in_category, name='product_all'),
    path('<slug:category_slug>/', product_in_category, name='product_in_category'),
    path('<int:id>/<product_slug>/', product_detail, name='product_detail'),
    path('search', search, name='search'),
]

order/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from accounts.models import User
from shop.models import Product
from coupon.models import Coupon


# Create your models here.
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    tel = models.CharField(blank=True, max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    coupon = models.ForeignKey(Coupon, on_delete=models.PROTECT, related_name='order_coupon', null=True, blank=True)
    discount = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100000)])

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f'Order {self.id} '

    def get_total_product(self):
        return sum(item.get_item_price() for item in self.items.all())

    def get_total_price(self):
        total_product = self.get_total_product()
        return total_product - self.discount


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name='order_products')
    price = models.IntegerField(blank=True)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_item_price(self):
        return self.price * self.quantity



import hashlib
from .iamport import payments_prepare, find_transaction


class OrderTransactionManager(models.Manager):
    def create_new(self, order, amount, success=None, transaction_status=None):
        if not order:
            raise ValueError("주문 정보 오류")

        order_hash = hashlib.sha1(str(order.id).encode('utf-8')).hexdigest()
        email_hash = str(order.email).split("@")[0]
        final_hash = hashlib.sha1((order_hash + email_hash).encode('utf-8')).hexdigest()[:10]
        merchant_order_id = str(final_hash)  # 동영상 강의에서 변경

        payments_prepare(merchant_order_id, amount)

        transaction = self.model(
            order=order,
            merchant_order_id=merchant_order_id,
            amount=amount
        )

        if success is not None:
            transaction.success = success
            transaction.transaction_status = transaction_status

        try:
            transaction.save()
        except Exception as e:
            print("save error", e)

        return transaction.merchant_order_id

    def get_transaction(self, merchant_order_id):
        result = find_transaction(merchant_order_id)
        if result['status'] == 'paid':
            return result
        else:
            return None


class OrderTransaction(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    merchant_order_id = models.CharField(max_length=120, null=True, blank=True)
    transaction_id = models.CharField(max_length=120, null=True, blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    transaction_status = models.CharField(max_length=220, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    objects = OrderTransactionManager()

    def __str__(self):
        return str(self.order.id)

    class Meta:
        ordering = ['-created']


def order_payment_validation(sender, instance, created, *args, **kwargs):
    if instance.transaction_id:
        import_transaction = OrderTransaction.objects.get_transaction(merchant_order_id=instance.merchant_order_id)
        merchant_order_id = import_transaction['merchant_order_id']
        imp_id = import_transaction['imp_id']
        amount = import_transaction['amount']

        local_transaction = OrderTransaction.objects.filter(merchant_order_id=merchant_order_id, transaction_id=imp_id,
                                                            amount=amount).exists()

        if not import_transaction or not local_transaction:
            raise ValueError("비정상 거래입니다.")


import django.db.models.signals

django.db.models.signals.post_save.connect(order_payment_validation, sender=OrderTransaction)

order/forms.py
from django import forms

from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['user', 'tel', 'email', 'address', 'postal_code']

order/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from cart.cart import Cart
from .forms import *

# Create your views here.

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        # 입력받은 정보를 후처리
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            if cart.coupon:
                order.coupon = cart.coupon
                order.discount = cart.get_discount_total()
                order.save()
            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'], price=item['price'],
                                         quantity=item['quantity'])
            cart.clear()

            return render(request, 'order/created.html', {'order': order})
    else:
        form = OrderCreateForm()
    return render(request, 'order/create.html', {'cart': cart, 'form': form})


# JS 동작하지 않는 환경에서도 주문은 가능해야한다.
def order_complete(request):
    cart = Cart(request)
    order_id = request.GET.get('order_id')
    order = get_object_or_404(Order, id=order_id)
    orderitem = OrderItem.objects.all()
    orderitem = orderitem.filter(order_id__exact=order_id)
    if order_id:
        query = Q()
        for i in order_id:
            query = query | Q(order_id=i)
            orderitem = orderitem.filter(query)
            cart.clear()
    if order.paid is True:
        for i in range(len(order.items.all())):
            change = order.items.all()[i].product
            change.stock -= order.items.all()[i].quantity
            change.save()
            if change.stock < 5:
                change.stock += 20
                change.save()
    cart.clear()

    return render(request, 'order/created.html', {'order': order, 'orderitem':orderitem })


def order_list(request):
    orders = Order.objects.all()
    orderitem = OrderItem.objects.all()
    return render(request, 'order/order_list.html', {'orders': orders, 'orderitem':orderitem,})



from django.views.generic.base import View
from django.http import JsonResponse


class OrderCreateAjaxView(View):
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return JsonResponse({"authenticated": False}, status=403)

        cart = Cart(request)
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if cart.coupon:
                order.coupon = cart.coupon
                order.discount = cart.get_discount_total()
            order.save()
            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'], price=item['price'],
                                         quantity=item['quantity'])
            # cart.clear()
            data = {
                "order_id": order.id
            }
            return JsonResponse(data)
        else:
            return JsonResponse({}, status=401)


class OrderCheckoutAjaxView(View):
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return JsonResponse({"authenticated": False}, status=403)

        order_id = request.POST.get('order_id')
        order = Order.objects.get(id=order_id)
        amount = request.POST.get('amount')

        try:
            merchant_order_id = OrderTransaction.objects.create_new(
                order=order,
                amount=amount
            )
        except:
            merchant_order_id = None

        if merchant_order_id is not None:
            data = {
                "works": True,
                "merchant_id": merchant_order_id
            }
            return JsonResponse(data)
        else:
            return JsonResponse({}, status=401)


class OrderImpAjaxView(View):
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return JsonResponse({"authenticated": False}, status=403)

        order_id = request.POST.get('order_id')
        order = Order.objects.get(id=order_id)

        merchant_id = request.POST.get('merchant_id')
        imp_id = request.POST.get('imp_id')
        amount = request.POST.get('amount')

        try:
            trans = OrderTransaction.objects.get(
                order=order,
                merchant_order_id=merchant_id,
                amount=amount
            )
        except:
            trans = None

        if trans is not None:
            trans.transaction_id = imp_id
            # trans.success = True
            trans.save()
            order.paid = True
            order.save()

            data = {
                "works": True
            }
            return JsonResponse(data)
        else:
            return JsonResponse({}, status=401)


from django.contrib.admin.views.decorators import staff_member_required


@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'order/admin/detail.html', {'order': order})

order/templates/order/create.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}
Checkout
{% endblock %}

{% block script %}
<script type="text/javascript">
    csrf_token = '{{csrf_token}}';
    order_create_url = '{% url "orders:order_create_ajax" %}';
    order_checkout_url = '{% url "orders:order_checkout" %}';
    order_validation_url = '{% url "orders:order_validation" %}';
    order_complete_url = '{% url "orders:order_complete" %}';
</script>

<script src="https://cdn.iamport.kr/js/iamport.payment-1.1.5.js" type="text/javascript"></script>

{% load static %}
<script src="{% static 'js/checkout.js' %}" type="text/javascript"></script>
{% endblock %}

{% block content %}
<style>
 .row{
 width:80%;
 margin:3% auto;
 }
 .alert-info {
    color: #fff;
    background-color: #666;
    border-color: #666;
}
.alert-success {
    color: #fff;
    background-color: #999;
    border-color: #999;
}
table{
 width:300px;
 height: 250px;
}
form-control{
    width:300px;}
</style>

<div class="row">
    <div class="col">
        <div class="alert alert-info" role="alert">주문 내역</div>
        <ul class="list-group">
            {% for item in cart %}
                <li class="list-group-item">
                    {{item.product.name}} {{item.quantity}}개 :
                    <span>{{item.total_price|intcomma}}</span>
                </li>
            {% endfor %}
            {% if cart.coupon %}
                <li class="list-group-item">
                    "{{cart.coupon.code}}" ( - {{cart.coupon.amount|intcomma}})
                    <span> {{cart.get_total_discount|intcomma}}</span>
                </li>
            {% endif %}
        </ul>
        <div class="alert alert-success" role="alert">총 가격 : {{cart.get_total_price|intcomma}}</div>
        <form action="" method="post" class="order-form">{% csrf_token %}
            <table class="t1">
                <thead>
                <tr>
                    <td class="t1-baqh"></td>
                    <td class="t1-in">
                        <input type="hidden" class="form-control" name="user" id="user1" placeholder="아이디"
                               value="{{ user.id }}">
                    </td>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td class="t1-baqh">전화번호: </td>
                    <td class="t1-in">
                        <input type="text" class="form-control" name="tel" id="tel1" placeholder="전화번호를 입력해주세요"
                               value="{{ user.tel }}"style="width:150%">
                    </td>
                </tr>
                <tr>
                    <td class="t1-baqh">이메일: </td>
                    <td class="t1-in">
                        <input type="text" class="form-control" name="email" id="email2" placeholder="이메일을 입력해주세요"
                               value="{{ user.email }}"style="width:150%">
                    </td>
                </tr>
                <tr>
                    <td class="t1-baqh">주소: </td>
                    <td class="t1-in">
                        <input type="text" class="form-control" name="address" id="address1" placeholder="주소를 입력해주세요"
                               value="{{ user.address }}"style="width:150%">
                    </td>
                </tr>
                <tr>
                    <td class="t1-baqh">우편번호: </td>
                    <td class="t1-in">
                          <input type="number" class="form-control" name="postal_code" id="postal_code1" placeholder="우편번호를 입력해주세요"
                                 value="{{ user.postal_code }}"style="width:150%">
                    </td>
                </tr>
                </tbody>
            </table>
            {% csrf_token %}
            <input type="hidden" name="pre_order_id" value="0">
            <input type="hidden" name="amount" value="{{cart.get_total_price|intcomma}}">
            <input type="submit" class="btn btn-outline-secondary float-right" value="구매하기">
        </form>
    </div>
</div>
{% endblock %}

order/templates/order/created.html
{% extends 'base.html' %}
{% block title %}

{% endblock %}

{% block content %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>주문완료</title>
    <script>
         $(function(){ /* 윈도우에 스크롤이 300px 이상 생기면
        go_top 나타남, 아니라면 사라짐 */
        $(window).scroll(function(){
            if($(this).scrollTop()>=500){
                $('.go_top').fadeIn();

            }else{
                $('.go_top').fadeOut();

            }
        });
        // go_top 버튼 클릭하면 html,body의 스크롤양이 0으로 바뀌도록 0.5s 함
        $('.go_top').click(function(e){
            e.preventDefault();
            $('html, body').stop().animate({scrollTop:0},500);
        }); });
    </script>
    <style>
    /* 위로가기 버튼 */
    .go_top{
            width:40px;
            height:40px;
            position: fixed;
            background:#333;
            color:#fff;
            right:50px;
            bottom:50px;
            text-align: center;
            line-height: 40px;

            display:none;
    }
        *{
        <!--        css초기화! base.html에 적용되어있는 스타일 상태를 해제함-->
        font-family : 'Noto Sans KR', sans-serif;
        margin:0;

        }
        #order_created_title{
        <!-- 주문 완료 -->

        margin-bottom:3%;
        font-weight:800;
        text-align:center;
        color:#666;

        }
        .order_created_content{
         margin:0 auto;
         width:80%;
         height:100%;
       <!--  border:1px solid black; -->
         position:relative;
         margin-top:50px;


        <!--    세로 가운데 정렬     -->
        }

        .order_created_content2{
        border: 0px solid red;
        border-bottom:1px solid black;
        height:300px;
        display: flex;
        align-items: center;
        margin:0 auto;
        }
        .order_created_icon{
        padding-left:30%;
        margin-right:2%;




        }
        #order_created_contents{
        display:block;


<!--        border:1px solid blue;-->
        }
        .sub_contents{
        display:block;
        margin-top:100px;
       }

       #myorder{
        color:#ff7c98;
       }

       .orcre_title{
       font-weight:600;}

         .delete-button-input{
                width:150px;
                height:50px;
                opacity:0.6;
                border-radius:3%;
                margin-left:88%;
                font-weight: bold;
                border:none;
                text-align:center;
          }
               .delete-button-input:hover {

                     opacity:1;
               }
<!--결제정보-->
        .tg  {border-collapse:collapse;border-spacing:0;}
        .tg td{border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;
          padding:10px 5px;word-break:normal;}
        .tg th{border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:14px;font-weight:normal;
          overflow:hidden;padding:10px 5px;word-break:normal;}
        .tg .tg-baqh{background-color:#c0c0c0; color: #ffffff; font-weight:bold;  text-align:center;vertical-align:top}
        .tg .tg-0lax{ padding-left:20px;background-color:#efefef; text-align:left;vertical-align:top}
<!-- 주문 상품 정보 -->

        .tg th{border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:14px;font-weight:normal;
          overflow:hidden;padding:10px 5px;word-break:normal;}
        .tg .tg-908g{color:#ffffff; background-color:#c0c0c0;border-color:#efefef;font-weight:bold;text-align:center;vertical-align:top}
        .tg .tg-li6d{ background-color:#efefef; border-color:#efefef;text-align:center;vertical-align:top}
        .tg .tg-ly6r{background-color:#efefef; border-color:#efefef;text-align:center;vertical-align:top}
    </style>
</head>
<body>
<br>
<h4 id="order_created_title">주문완료</h4>


<hr>
<div class="order_created_content">
    <div class="order_created_content2">
    <image src="https://postfiles.pstatic.net/MjAyMjEwMTRfOTYg/MDAxNjY1NzI4MTc5Mjg4.geEZoaFQIXplEOlbeDjcXRixKpu08wYrRMBr5LnzDzUg.uYjSldrnc0VbhmT-oIR63m7sGuM28o9mFXyudX0rFa0g.PNG.pandk23/check.png?type=w773" alt="주문완료체크" class="order_created_icon" id="order_created_contents"></image>
         <div id="order_created_contents">
        <h5  class="orcre_title">고객님의 주문이 완료되었습니다.</h5>

<!--        <div class="sub_contents">-->
        <p>주문내역 및 배송에 관한 안내는 <a href="{% url 'orders:order_list' %}" id="myorder">주문조회</a>를 통하여 확인 가능합니다.</p>

        <p>주문번호 : {{order.id}} <br>
       주문날짜 : {{order.updated|date:'Y-m-d H:i'}} </p>
    </div>
    </div>
<br><br><br>
    <h5 style="font-weight:600;">&nbsp 결제 정보  </h5>
<table class="tg" style="undefined;table-layout: fixed; width: 100%;">
<colgroup>
<col style="width: 10%">
<col style="width: 90%">
</colgroup>
<tbody>
  <tr>
                      {% load humanize %}

    <td class="tg-baqh">결제 금액</td>
    <td class="tg-0lax">{{order.get_total_price|intcomma}}원</td>
  </tr>

  <tr>
    <td class="tg-baqh">고객 성함</td>
    <td class="tg-0lax">{{order.user.username}}님</td>
  </tr>
  <tr>
    <td class="tg-baqh">받는 주소</td>
    <td class="tg-0lax">{{order.address}} {{order.postal_code}}</td>
  </tr>
  <tr>
    <td class="tg-baqh">전화 번호</td>
    <td class="tg-0lax">{{order.tel}}</td>
  </tr>
  <tr>
    <td class="tg-baqh">전자 주소</td>
    <td class="tg-0lax">{{order.email}}</td>
  </tr>
</tbody>
</table>

<br><br><br>
<h5 style="font-weight:600;">&nbsp 주문 상품 정보  </h5>
<table class="tg" style="undefined;table-layout: fixed; width: 100%; ">
<colgroup>
<col style="width: 40%">
<col style="width: 25%">
<col style="width: 15%">
<col style="width: 20%">
</colgroup>
<thead>
    <th class="tg-908g">이미지</th>
    <th class="tg-908g">상품명</th>
    <th class="tg-908g">수량</th>
    <th class="tg-908g">개별가격</th>
  </tr>
</thead>
<tbody>

    {% for item in order.items.all %}

  <tr>
    <td class="tg-li6d">
       <a href="{{item.product.get_absolute_url}}">
        <img src="{{item.product.image.url}}" style="height:200px;"></a></td>
    <td class="tg-ly6r" style="padding-top:100px; font-weight:600;">{{item.product.name}}</td>
    <td class="tg-ly6r" style="padding-top:100px; font-weight:600;">{{item.quantity }}</td>
    <td class="tg-ly6r" style="padding-top:100px; font-weight:600;">{{item.product.price|intcomma}}</td>
  </tr>

    {% endfor %}


        </tbody>
</table>

<br><br><br>
<!--    <a href="{% url 'orders:order_delete' %}"> <input type="button" class="delete-button-input" value="주문취소하기"> </a>-->
    <a href="{% url 'shop:product_all' %}"> <input type="button" class="delete-button-input" value="쇼핑 계속하기"> </a>


<a href="" class="go_top">
    <i class="fas fa-arrow-up"></i>

</a>





</div>
</body>
</html>
{% endblock %}

order/templates/order/order_list.html
{% extends 'base.html' %}
{% block title %} Order List {% endblock %}

{% block content %}
<style>
 .deletetitle{
                font-weight: 500;
                margin-left:10%;
                margin-top:1%;
                color:#666;
          }
  .deletetitle2{
                font-weight: 500;
                margin-left:10%;
                margin-top:1%;
                color:#666;
                font-size:16px;
  }
  th, td {
  text-align:center;}

  a:hover{
  text-decoration:none;}

  .ordertr:hover{
  background-color:#efefef; border-color:#efefef;

  }
</style>
<h3 class="deletetitle">주문내역 조회</h3>
<h5 class="deletetitle2">고객님께서 주문하신 내역의 리스트를 보여드립니다. <a href="#" ><i class="fa-solid fa-backward" onClick="javascript:history.go(-1);" style="margin-left:80%;">&nbsp 마이페이지</i></a>
 </h5>
<hr>

<div class="row mt-5" >
    <div class="col-12">
        <table class="table table-light" style="width:80%; margin:0 auto; margin-top:30px; margin-bottom:100px;">
            <thead style="color:#ffffff; background-color:#c0c0c0;border-color:#efefef;">
            <tr>

                <th scope="col"> 주문번호</th>
                <th scope="col">주문날짜</th>
                 <th scope="col">주문금액</th>

            </tr>
            </thead>
            <tbody class="text-dark">
               {% for order in orders %}
               {% if request.user == order.user %}


            <tr class="ordertr">
                <td scope="row"><a href="../complete/?order_id={{ order.id }}">{{order.id}}</a></td>
                <td scope="row"><a href="../complete/?order_id={{ order.id }}">{{order.updated|date:'Y년m월d일 H시i분'}}</a></td>
                {% load humanize %}
                <td scope="row"><a href="../complete/?order_id={{ order.id }}">{{order.get_total_price| intcomma }}원</a></td>

            </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
 <script language="JavaScript" type="text/JavaScript">
        var banner = new Array();

         banner[0]="<a href='#'><img src='../../static/blog/image/banner01.png' border='0' width='100%' height='100%'></a>";
         banner[1]="<a href='#'><img src='../../static/blog/image/banner02.png' width='100%' height='100%'></a>";
         banner[2]="<a href='#'><img src='../../static/blog/image/banner03.png' border='0' width='100%' height='100%'></a>";
         banner[3]="<a href='#'><img src='../../static/blog/image/banner04.png' border='0' width='100%' height='100%'></a>";
         banner[4]="<a href='#'><img src='../../static/blog/image/banner05.png' border='0' width='100%' height='100%'></a>";
         banner[5]="<a href='#'><img src='../../static/blog/image/banner06.png' border='0' width='100%' height='100%'></a>";
         banner[6]="<a href='#'><img src='../../static/blog/image/banner07.png' border='0' width='100%' height='100%'></a>";


         var random_banner = Math.floor(Math.random()*(banner.length));
     </script>
     <script>document.write(banner[random_banner]);</script>

{% endblock %}